### Create a new transaction
POST http://localhost:5000/transactions/new
Content-Type: application/json

{
  "sender": "d4ee26eee15148ee92c6cd394edd974e",
  "recipient": "someone-other-address",
  "amount": 5
}
