### Publish notary entry
POST http://localhost:3000/chain/entry
Content-Type: application/json

{
  "hash": "0x9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a02",
  "filename": "testFileName 2",
  "comment": "test comment 2"
}

### Request notary entry
GET http://localhost:3000/chain/entry/0x9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a16